spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret=test-secret-key-for-github-actions

aws.region=ap-south-1
aws.s3.bucket=employee-management-api-shifa

spring.jpa.hibernate.ddl-auto=create-drop